# Generated by Django 4.2.5 on 2023-09-20 17:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=datetime.datetime(2023, 9, 20, 17, 11, 9, 923220, tzinfo=datetime.timezone.utc), upload_to='products/images'),
            preserve_default=False,
        ),
    ]
