# Generated by Django 4.2.5 on 2023-09-28 03:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('reception_type',
                 models.CharField(choices=[('delivery', 'Delivery'), ('pickup', 'Pickup')], max_length=8)),
                ('customer',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders',
                                   to=settings.AUTH_USER_MODEL)),
                ('delivery_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('unit_price', models.IntegerField()),
            ],
        ),
    ]
