# Generated by Django 4.2.5 on 2023-11-06 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='unit_price',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_price',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('click', 'Click')], default=10, max_length=5),
            preserve_default=False,
        ),
    ]
