# Generated by Django 4.2.5 on 2023-11-05 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date',
            new_name='created_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
