# Generated by Django 4.2.5 on 2023-11-03 13:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='contacts',
            field=models.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='settings',
            name='picture',
            field=models.ImageField(default=datetime.datetime(2023, 11, 3, 13, 42, 4, 913834, tzinfo=datetime.timezone.utc), upload_to='company/images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='qr_code',
            field=models.ImageField(default=datetime.datetime(2023, 11, 3, 13, 42, 12, 456757, tzinfo=datetime.timezone.utc), upload_to='company/images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='qr_text',
            field=models.CharField(default='hello', max_length=250),
        ),
    ]
