# Generated by Django 4.2.5 on 2023-11-03 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phone',
            options={'verbose_name_plural': 'phone'},
        ),
    ]
