# Generated by Django 4.2.5 on 2023-11-04 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_settings_contacts_settings_picture_settings_qr_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='contacts',
            field=models.JSONField(default=dict),
        ),
    ]
