# Generated by Django 4.2.5 on 2023-11-03 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_phone_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phone',
            old_name='phone',
            new_name='phone_number',
        ),
    ]
