# Generated by Django 4.2.5 on 2023-11-04 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_settings_contacts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name_plural': 'About'},
        ),
        migrations.AlterModelOptions(
            name='social',
            options={'verbose_name_plural': 'Social'},
        ),
    ]
