# Generated by Django 4.2.5 on 2023-11-04 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_alter_about_options_alter_social_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='contacts',
        ),
        migrations.AddField(
            model_name='settings',
            name='bot_url',
            field=models.CharField(default='hello', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='phone',
            field=models.CharField(default='hello', max_length=100),
            preserve_default=False,
        ),
    ]
