# Generated by Django 4.2.5 on 2023-11-04 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_remove_settings_contacts_settings_bot_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='qr_text',
            field=models.CharField(max_length=250),
        ),
    ]
