# Generated by Django 4.2.5 on 2023-11-04 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_alter_settings_qr_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='logo',
            field=models.FileField(upload_to='company/images'),
        ),
    ]
